#!/usr/bin/env bash
# Bash script that transfers a file from client to server
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses
path="$1"
ip="$2"
username="$3"
sshkeypath="$4"

#Check if parameters are greater than 3
if [ $# -lt 3 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	#Connect to the ssh server
	scp -o StrictHostKeyChecking=no -i "$sshkeypath" "$path" "$username@$ip:~/"
fi
