#!/usr/bin/env bash
# A Bash script that prints the name of the files in the current directory, line by line, including only the parts after the dash

for item in *;
   do
     echo "$item" | cut -d '_' -f2
   done
